# Site settings
title: Oscar's Profile
email: osveliz@miners.utep.edu
description: > # this means to ignore newlines until "baseurl:"
  Oscar's profile
baseurl: "/project-gh-pages"
url: "http://osveliz.github.io/patchwork-gh-pages-24/"
twitter_username: osveliz
github_username:  osveliz
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
