# Site settings
title: Oscar's Profile
email: osveliz@miners.utep.edu
description: > # this means to ignore newlines until "baseurl:"
 Oscar's Profile
baseurl: "/patchwork-gh-pages-24"
url: "http://osveliz.github.io"
twitter_username: osveliz
github_username:  osveliz
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
